name = "Make²"
author = "Zesty Modpack Authors"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4046190db9502dfbd0ae58bda70d10ba4ed8a06ec34483a46aec407acdf9e3e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.138"
