name = "Make²"
author = "Zesty Modpack Authors"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6354e0058fa42311258902d7e9d30a85c008e1b604db5e2e832d8d45e2872942"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
